on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ena-sample-registration-action
        uses: emo-bon/ena-sample-registration-action@main
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DROPBOX_PRO: "<production_url>"
          DROPBOX_DEV: "https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/"
          QUERY_PRO: "https://www.ebi.ac.uk/ena/portal/api/search?result=sample&query=(sample_alias={alias})"
          QUERY_DEV: "https://wwwdev.ebi.ac.uk/ena/portal/api/search?result=sample&query=(sample_alias={alias})"
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4