on:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ena-sample-registration-action
        uses: emo-bon/ena-sample-registration-action@main
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
